-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('GENERIC', 'NEW_APPOINTMENT', 'APPOINTMENT_CONFIRMED', 'APPOINTMENT_CANCELED', 'APPOINTMENT_COMPLETED', 'SYSTEM_UPDATE');

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN     "type" "NotificationType" NOT NULL DEFAULT 'GENERIC';
